### ISSUE TITLE
Issue on training code

### ISSUE THREAD

**Issue by ntkien1904** [HKUDS/AnyGraph#2]
Dear author,

Thank you so much for sharing this amazing work.

I tried to execute the training code: `python main.py --dataset link2+link1 --save pretrain_link2`  but encountered error as attached below. May you suggest a quick fix on this issue? Thank you.

![Screenshot 2024-09-15 at 6 59 50 PM](https://github.com/user-attachments/assets/0ba982c1-b733-4eea-9057-f4cd124e611a)

**Comment by akaxlh** [comment]
Thank you for your interest in this work. I re-clone the github code and run it, but cannot observe this error message. Maybe it's some of your editing causing this error. I suggest check the JointTrnData class in data_handler.py of your local copy, or if your code is using JointTrnData. The __getitem__ function of this class should return an unpacked list with length three, and an integer for the dataset id.
